services:
  traefik:
    image: traefik:v3.6
    environment:
      - LEGO_CA_CERTIFICATES="/etc/traefik/ca_certificate.pem"
      - TZ="Europe/Berlin"
    labels:
      - traefik.enable=true
      # HTTPS dashboard router
      - traefik.http.routers.dashboard-https.rule=Host(`traefik.home`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard-https.entrypoints=websecure
      - traefik.http.routers.dashboard-https.tls=true
      - traefik.http.routers.dashboard-https.service=api@internal
      # HTTP dashboard router (no TLS)
      - traefik.http.routers.dashboard-http.rule=Host(`traefik.home`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard-http.entrypoints=web
      - traefik.http.routers.dashboard-http.service=api@internal
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/traefik/ca_certificate.pem:/etc/traefik/ca_certificate.pem:ro
      - /opt/traefik/acme.json:/etc/traefik/acme.json
    networks:
      - traefik
      - internal

networks:
  traefik:
  internal:
