services:
  traefik:
    image: traefik:v3.6
    command:
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    environment:
      - LEGO_CA_CERTIFICATES="/etc/traefik/ca_certificate.pem"
      - TZ="Europe/Berlin"
    labels:
      # HTTPS dashboard router
      - traefik.http.routers.dashboard-https.rule="Host('traefik.home') && (PathPrefix('/api') || PathPrefix('/dashboard'))"
      - traefik.http.routers.dashboard-https.entrypoints="websecure"
      - traefik.http.routers.dashboard-https.tls=true
      - traefik.http.routers.dashboard-https.service="api@internal"
      - traefik.http.routers.dashboard-https.middlewares="auth"
      # HTTP dashboard router (no TLS)
      - traefik.http.routers.dashboard-http.rule="Host('traefik.home') && (PathPrefix('/api') || PathPrefix('/dashboard'))"
      - traefik.http.routers.dashboard-http.entrypoints="web"
      - traefik.http.routers.dashboard-http.service="api@internal"
      - traefik.http.routers.dashboard-http.middlewares="auth"
      # Basic auth credentials
      - traefik.http.middlewares.auth.basicauth.users="cedric:$apr1$FOTwjesX$uhGkQ3kKkS8clmfZgpAhx/"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/traefik/traefik.yml:/etc/traefik/traefik.yml 
      - /opt/traefik/ca_certificate.pem:/etc/traefik/ca_certificate.pem
    networks:
      - traefik

networks:
  traefik:
